### ISSUE TITLE
On Dnn 9.1.1, upgrading from Links 4.0.1 to 6.2.3 throws ambiguous error on page

### ISSUE THREAD

**Issue by valadas** [DNNCommunity/DNN.Links#14]
Error: Links is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: C:\inetpub\dnn\DesktopModules\Links\Links.ascx.vb(557): error BC30560: 'LinkController' is ambiguous in the namespace 'DotNetNuke.Modules.Links'. ---> System.Web.HttpCompileException: C:\inetpub\dnn\DesktopModules\Links\Links.ascx.vb(557): error BC30560: 'LinkController' is ambiguous in the namespace 'DotNetNuke.Modules.Links'. at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath) at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath) at DotNetNuke.UI.ControlUtilities.LoadControl[T](TemplateControl containerControl, String ControlSrc) at DotNetNuke.UI.Modules.WebFormsModuleControlFactory.CreateModuleControl(TemplateControl containerControl, ModuleInfo moduleConfiguration) at DotNetNuke.UI.Modules.ModuleControlFactory.LoadModuleControl(TemplateControl containerControl, ModuleInfo moduleConfiguration) at DotNetNuke.UI.Modules.ModuleHost.LoadModuleControl() --- End of inner exception stack trace ---

**Comment by valadas** [comment]
Thanks @Rhilliard514 I mainly logged this to one day go correct the issue this the old files are automatically cleaned-up on upgrade.

**Comment by fprati** [comment]
same here, thank you for the hint.

**Comment by valadas** [comment]
I added cleanup scripts in the latest release that seams to fix this. If it is not the case, feel free to reopen this or a new issue.

**Comment by moorecreative** [comment]
Hmm, I'm not sure it's worth reopening since the newer 7.0.0 may address the issue... BUT
on a DNN 8 instance, I had the same error message. After removing the two DLLs from the bin folder:
DotNetNuke.Modules.Links.SqlDataProvider.dll
DotNetNuke.Modules.Links.dll
I see a different error message now displayed:

Error: Links is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: The type initializer for 'DotNetNuke.Modules.Links.DataProvider' threw an exception. ---> System.TypeInitializationException: The type initializer for 'DotNetNuke.Modules.Links.DataProvider' threw an exception. ---> System.ArgumentNullException: Value cannot be null. Parameter name: type at System.Activator.CreateInstance(Type type, Boolean nonPublic) at System.Activator.CreateInstance(Type type) at DotNetNuke.Framework.Reflection.CreateObject(String ObjectProviderType, String ObjectProviderName, String ObjectNamespace, String ObjectAssemblyName, Boolean UseCache) at DotNetNuke.Framework.Reflection.CreateObject(String ObjectProviderType, String ObjectNamespace, String ObjectAssemblyName) at DotNetNuke.Modules.Links.DataProvider.CreateProvider() --- End of inner exception stack trace --- at DotNetNuke.Modules.Links.LinkController.GetLinks(Int32 ModuleId) at DotNetNuke.Modules.Links.Links.Page_Load(Object sender, EventArgs e) --- End of inner exception stack trace ---
