### ISSUE TITLE
Page Links mode - Mark current page "Active" in listing which can be configured via CSS

### ISSUE THREAD

**Issue by JaySMa** [DNNCommunity/DNN.Links#28]
## Is your feature request related to a problem?
No problem or issues.

## Describe the solution you'd like
When using the Links module to list pages on your website, it would be nice if the current page being viewed (which is also listed as a link) can have a class named "Active" or something similar so that it's highlighted or bolded in the links listing.

For e.g.:
Home
_**This**_
That
Other

I'm on "This" page.

**Comment by valadas** [comment]
I took a look into this and a link in the Links module could be one of many things, we don't have a great way of knowing in context if any given link represents the current page. I would recommend using DDR Menu for this purpose instead of the links module. I'll close this issue but if anyone is willing to work on this enhancement, please comment and I'll reopen.
