### ISSUE TITLE
Can no longer create links to local documents

### ISSUE THREAD

**Issue by chood601** [DNNCommunity/DNN.Links#37]
With previous versions of the Links module it was possible to create links to local files such as PDF documents or Excel spreadsheets.  We use this functionality with our internal Intranet site. Yes, we could store our documents inside of the site itself and link to them that way, but we have a rather large repository of files on our file server and are not really interested in importing those into the site and managing them there.

With the new version, file:/// requests no longer seem to work.  I've tried using the following variations:

file:///g:\folder\file.pdf
file:///g:/folder/file.pdf

Using a backslash character results in an error.  Using the forward slash is accepted but simply doesn't work when the link is clicked.

## Software Versions
- DNN: 09.03.02
- Module: 07.00.01

**Comment by valadas** [comment]
This is actually a browser protection rather than a change in the module:

![image](https://user-images.githubusercontent.com/6371568/106565497-e6b3a080-64fc-11eb-92ba-319a6a9e45ca.png)

I think there are some browser extensions or configs that may let it work for you like https://chrome.google.com/webstore/detail/enable-local-file-links/nikfmfgobenbhmocjaaboihbeocackld?hl=en
