### ISSUE TITLE
Could not find stored procedure 'dnnLinks_GetLinks'.

### ISSUE THREAD

**Issue by dlloyd525** [DNNCommunity/DNN.Links#49]
## Describe the bug
After upgrading to DNN 9.4.4, I am seeing this error in the admin logs.  It appears to be caused by the module indexer.  I have verified that 'SC_dnnLinks_GetLinks' exists as a stored procedure.

## Software Versions
- DNN: 09.04.04
- Module: 07.00.01

## To Reproduce
It happens when the module indexer runs.

## Expected behavior
No error.

## Error log
AbsoluteURL:
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:744c617a-63a9-4b04-8d7d-a936320b77eb
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:EywjChDU6EGiOKJaJrxZvw9I2J4=
Message:Could not find stored procedure 'dnnLinks_GetLinks'.
StackTrace:
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at PetaPoco.Database.<ExecuteReader>d__149`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at DotNetNuke.Modules.Links.Components.LinkController.GetLinks(Int32 moduleId)
   at DotNetNuke.Modules.Links.Components.FeatureController.GetModifiedSearchDocuments(ModuleInfo moduleInfo, DateTime beginDateUtc)
   at DotNetNuke.Services.Search.ModuleIndexer.IndexSearchDocuments(Int32 portalId, ScheduleHistoryItem schedule, DateTime startDateLocal, Action`1 indexer)

InnerMessage:
InnerStackTrace:

Source:.Net SqlClient Data Provider
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:

**Comment by TekkGuy** [comment]
Is this module no longer being supported by anyone? I just upgraded my DNN instance to v9.3.2 (on my way up to the latest version), and started seeing this error too. I have the Links Module in several places on several sites ... 

I am so confused as to why DNN would abandon modules that have no direct replacement and were included in the core installation of previous versions. Nice way to abandon your users ... ::Sigh::

**Comment by valadas** [comment]
You need to understand that both Dnn and these modules a free and open source. I and many other contributors have spent countless hours maintaining most of these modules, but you need to understand this is free labor and we do what we can with the limited amount of free time we have. I should do a run of updating some of these modules in preparation for Dnn 10, but cannot guarantee a timeframe.

**Comment by TekkGuy** [comment]
I completely understand that the people currently maintaining this and several other "free" modules are doing this on their own time for free. I am also very grateful for your and everyone else's contribution to that effort.

However, the point I was getting at is that this module was included as part of the PAID version of DNN. During their evolution, DNN decided at some point to stop maintaining these modules and instead excise them as part of a "free" community project, and they never created or offered a direct replacement. So it ends up that paying customers, such as myself, that started with a DNN version where these modules were included, and continued upgrading through the years, are now left between a rock and a hard place when those upgrades cause system failures due to incompatibilities from excised modules that are not regularly maintained as they were long ago when they were included. 

It is hard enough at times to manage/maintain our DNN websites with regards to framework and module versions ... but when you upgrade and a module that was included breaks and has absolutely no replacement or an updated version ... makes maintenance all the more difficult.

I would try downloading and compiling the module myself, but I do not have the required software to do that at this point in time. :-(

Again, thank you for all your hard work, it is most definitely appreciated.

**Comment by EPTamminga** [comment]
@TekkGuy : Visual Studio Code is all you need for building modules for DNN. VSC is free from Microsoft. 
https://code.visualstudio.com/

The source of the Links module is free as well, all available in this repository.

If you are not satisfied with paid subscriptions of DNN (a.k.a. Evoq) and you have a paid version yourself, I think that the best option would be to contact DNNCorp, since they would be responsible for their products.

**Comment by mathisjay** [comment]
@TekkGuy I'm curious about your 'PAID" comment.  Wouldn't it make sense to go back to whoever you paid and ask for support?  The Links module was never a "paid" module, it was a free open source module that some resellers (including DNN Corp) included in their solution which they sold to customers.    If you have a paid support contract with someone, I would go back to that person.  Alternatively, there are plenty of DNN consultants available that could fix this for you on a contract basis if you need immediate business-critical help.

**Comment by mitchelsellers** [comment]
Looking at the issue as reported by @TekkGuy It appears that it is an issue with a custom objectQualifier.

However, the call referenced in the code: https://github.com/DNNCommunity/DNN.Links/blob/bcbf5ab87452da346f7fdbd9b33a4099c653b5b6/Components/LinkController.cs#L238 

Has the proper structure. 

@TekkGuy Can you confirm that no errors occurred when installing the latest version?

**Comment by TekkGuy** [comment]
@mathisjay
We pay DotNetNuke directly for Evoq, we have always since day #1 of using DNN for our business, purchased a license directly from DotNetNuke. We never used the free/community/platform version for our production sites. DNNCorp's "paid" version is (from my understanding) basically added features to the free/platform version. Since it was initially bundled together, as I said, makes it a pain for those that upgraded through the years now having problems with a module we never "installed" separately.

**Comment by TekkGuy** [comment]
@EPTamminga 

Thank you for that information, however, a lot more is needed than just the IDE to edit the source code. In order to compile, you need to also have a functional "development" site of the correct DNN Platform version installed, with the source of the module within it. And there also seems to be other 3rd party items that are needed to compile the ZIP for installation. 

So, I have to work on getting my system up-to-speed with all the dependencies needed to be able to compile an installation version of this module.

**Comment by TekkGuy** [comment]
@mitchelsellers 

I can confirm that v7.0.1 which I have installed does not work. I have downloaded the source, and I see that "{databaseOwner}{objectQualifier}" is listed, but I am not sure if this version of the file in the source, is what was used to create the compiled version for 7.0.1. All I can tell you is that apparently the v7.0.1 Install, seems to be looking for the module without the DBOQ prefix to the Stored Procedure, which then throws an error because it cannot find the SP.

**Comment by EPTamminga** [comment]
@TekkGuy Development of a module does not need a DNN installation, only the referenced DLL's, preferably configured in your modules as a NuGet reference. Not much work and a normal way of working. 
Testing, of course, requires a functional test environment. But that is also normal 

You can combine the two (development and test) in a working DNN, but that is not what most DNN module developers do. The advantage is that testing (seems) easier, but the drawback is that testing in various DNN versions becomes much more complicated.

**Comment by mathisjay** [comment]
@TekkGuy 

You said "We pay" which suggests you are still paying for an Evoq license.  Please note that you do not pay DotNetNuke, you pay DNN Corp.  I know it can be a bit confusing, but my point is, I think you might be barking up the wrong tree.  DNN Corp likely does not even subscribe to the issues here as they depend on the community to support the platform and the fee modules and they focus on their Evoq product.  If you are expecting support because of the license you are paying, you probably need to contact DNN Corp directly.   

If I am wrong about your current subscription status and you need a consultant to help fix an immediate need, there are a variety of options you might look at.  I would start on the dnncommunity.org website where you can find agencies and MVPs and also a forum that might provide assistance.

**Comment by TekkGuy** [comment]
Ok ... FYI to anyone reading this thread ...

The release for download here (v7.0.1) ... is wrong. The update to fix this error exists in the source, however, the files used to compile v7.0.1 must have used an older copy of the source (before the fix).

I downloaded the current source, set up my system to be able to compile it (which took a little while), and performed the re-compile. The newly compiled version (using the source as of today 10/08/2020), works on DNN v9.3.2 and fixes the DBOQ error.

Hope this helps anyone coming across this same error.

**Comment by mitchelsellers** [comment]
@TekkGuy Glad you are set to go!  

@valadas Should we just re-release with a fix?  Bump versions?

**Comment by valadas** [comment]
@TekkGuy The release is not wrong, the fix came in after the release.

@mitchelsellers yes we should, it is on my very long todo list, when I do get to that, there are 22 issues to look at and 3 prs to review/merge and testing and a release. 

Everyone needs to understand that relating the the modules that used to come with Dnn (We call them the core modules), there are about 20 of them and we only have a handful of contributors and half a handful of active maintainers, so the few that maintain them (for free) have a long laundry list of work to accomplish. I'll try to take a look at doing that soon... But my list is long and like it was said by others, sponsorships do get line items higher up in that list 😄

**Comment by TekkGuy** [comment]
@valadas 

My apologies, I assumed that any changes accepted into the source were compiled into a final release. I didn't expect the available source to have uncompiled changes.

Just glad to have a working copy of this module again ... would have hated to have written an alternative to replace this everywhere it was used in our many sites.

Unfortunately, my programming language strength is geared to VB.Net as opposed to C#. Otherwise, maybe I could have been of more help.

Again, thank you all for your continued work on all things DNN.  :-)

**Comment by valadas** [comment]
Done in #50 will try to get a new release out soon...
