### ISSUE TITLE
Installer removes entry from codeSubdirectories in web.config

### ISSUE THREAD

**Issue by ggiordan** [DNNCommunity/DNN.Links#61]
## Describe the bug
After installing latest version, site crashed with the following error:
[HttpException (0x80004005): The files '/App_Code/csharp/file.cs' and '/App_Code/Links/DataProvider.vb' use a different language, which is not allowed since they need to be compiled together.]

The issue was that the installer removed the following entry from the web.config file:
```
      <codeSubDirectories>
	      <add directoryName="csharp"/>
	      <add directoryName="Links"/>
      </codeSubDirectories>
```
Adding the entry back resolves the issue.

## Software Versions
- DNN: 09.09.01
- Module: 08.00.00

## To Reproduce
1. Assuming there is a "<add directoryName="Links"/>" entry in the web.config
2. Install the module
3. The entry in the web.config file will have been removed

## Expected behavior
Don't remove the "<add directoryName="Links"/>" entry

## Error log
`[HttpException (0x80004005): The files '/App_Code/csharp/file.cs' and '/App_Code/Links/DataProvider.vb' use a different language, which is not allowed since they need to be compiled together.]

**Comment by hismightiness** [comment]
I actually think that one of your previous (or current) upgrades of this module didn't upgrade cleanly.  

I don't recall which version, but one of the DNN Links upgrades was supposed to delete a DLL and the related `App_Code\Links` folder upon upgrade, but it doesn't.  I'd suggest deleting the folder again as it was, restoring the web.config update, then looking for the old DLL in the bin folder and deleting that (leaving the new one in place).  

The old Links module code base was written in VB, but when the module was converted to a WAP instead of WSP, the relevant cleanup code was not included in the release.

**Comment by valadas** [comment]
Yeah, I can't make this happen, I am guessing it was some sort of fluke.
