### ISSUE TITLE
Looking for documentation on this module

### ISSUE THREAD

**Issue by shash99** [DNNCommunity/DNN.Links#76]
## Please summarize your question in one sentence
Looking for documentation on this module.

## Give a more extended description
When adding a link there is a message "This Module is configured to show dynamic Data.  Please use Modulesettings to change."  what does this mean?  Also, there is a setting called Get content:  What is this used for?

See screenshot below.

## Other comments or remarks
![2023-03-08_14-30-50](https://user-images.githubusercontent.com/5889823/223829273-a8ae2095-81e2-4d7d-9f6d-b88c28b80700.jpg)

**Comment by valadas** [comment]
I do not use this module much but if memory serves good:

1. If you are in a mode in settings that has it's own data sources (pages, etc.) instead of you defining the links, this message shows.
2. The module can fetch meta-data from links (can't remember the details but something like the page title and stuff) so GetConent fetches that meta-data so it can be used in templates.

I'll move this issue to a discussion unless there is some sort of bug with the features in which case I'll bring it back to an issue...

**Comment by valadas** [comment]
Oh, we don't have the option here to move it to a discussion, I'll close (we can still discuss on it) and reopen if it turns out there is an issue...
